# NUMPY

In [35]:
import numpy as np

In [36]:
# ARREGLO ES UNA LISTA EN PYTHON
# Ambos nos permite almacenar n datos
# Arreglo en numpy es mas rapido y compacto que una lista en python
# Arreglo consume menos memoria

In [37]:
lista = [14, 58, 36, 59,4,78,23,56]
type(lista)

list

In [38]:
arList = np.array(lista) # Array
type(arList)

numpy.ndarray

In [39]:
# Dimensiones del arreglo
arList.ndim

1

In [40]:
arList.size 
# nro elementos

8

In [41]:
arList.itemsize
# tamanio en byte del arreglo

4

In [42]:
arList.shape

(8,)

In [43]:
arList

array([14, 58, 36, 59,  4, 78, 23, 56])

In [44]:
arList[1]
arList[arList.size-1]

56

In [45]:
arList[1:3]

array([58, 36])

In [46]:
arList[1:5:2]

array([58, 59])

In [47]:
arList[::-1]

array([56, 23, 78,  4, 59, 36, 58, 14])

In [48]:
# CREAR SUB ARRAY
lista = [0,3,6]

In [49]:
for i in lista:
  print(arList[i])

14
59
23


In [50]:
arList[lista]

array([14, 59, 23])

In [51]:
arList[[0,3,6]]

array([14, 59, 23])

In [52]:
np.array([0,3,6]) # Array

array([0, 3, 6])

In [53]:
# np.array([0,3,6],dtype='f') 
np.array([0,3,6],dtype=np.float32) # Mas recomendable

array([0., 3., 6.], dtype=float32)

In [54]:
# np.array([0,3,6],dtype='i')
np.array([0,3,6],dtype=np.int32) # Mas recomendable

array([0, 3, 6])

In [55]:
# np.array([0,1,0],dtype='?')
np.array([0,1,0],dtype=np.bool) # Mas recomendable

<ipython-input-55-145695c0f0bc>:2: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array([0,1,0],dtype=np.bool) # Mas recomendable


array([False,  True, False])

In [56]:
np.arange(0,10)
np.arange(0,16,3) # Con salto

array([ 0,  3,  6,  9, 12, 15])

In [57]:
np.zeros(8)
np.ones(8,dtype=np.int32)

array([1, 1, 1, 1, 1, 1, 1, 1])

In [58]:
np.full(10,5) #(nro elementos, nro a almacenar)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [59]:
np.random.random(3)

array([0.96832081, 0.66156683, 0.37106151])

In [60]:
# np.random.random(6) # 6 nros aleatorios
np.random.randint(0,25,5) # Un arreglo de tamanio 10 en el rango de [0,25]

array([ 4, 18,  9, 22, 14])

In [61]:
np.linspace(0,10,5) # 5 elementos en el rango de [0,10] 

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

## Matriz

In [62]:
a= np.array([
          [1, 2, 3, 4, 5], 
          [10, 20, 30, 40, 50],
          [100, 200, 300, 400, 500]
          ])

In [63]:
a

array([[  1,   2,   3,   4,   5],
       [ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [64]:
# a[2][4]
a[2,4]

500

In [65]:
# a[1][1:4]
a[1, 1:4]

array([20, 30, 40])

In [66]:
a[1,[0,2,4]]

array([10, 30, 50])

In [67]:
a.ravel() # De una matriz a un arreglo unidimensional

array([  1,   2,   3,   4,   5,  10,  20,  30,  40,  50, 100, 200, 300,
       400, 500])

In [68]:
a

array([[  1,   2,   3,   4,   5],
       [ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [69]:
a.flatten() # COPIA !! retorna una copia arregla unidimensional

array([  1,   2,   3,   4,   5,  10,  20,  30,  40,  50, 100, 200, 300,
       400, 500])

In [70]:
a

array([[  1,   2,   3,   4,   5],
       [ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

Actualizar arreglo

In [71]:
a=np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
a[0:3]=20

In [73]:
a[[4,6,8]]=16

In [74]:
a

array([20, 20, 20,  3, 16,  5, 16,  7, 16,  9])

In [75]:
a = np.append(a,88)

In [76]:
a = np.delete(a,5) #(array, posicion)

Poder de shape

In [77]:
a=np.arange(0,15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [78]:
# a.shape = 3,5
a.shape = (3,5)

In [79]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [80]:
a.reshape(5,3) # METODO QUE GENERA UN NUEVO ARREGLO CON != DIMENSION PERO SIN MODIFICAR EL ORIGINAL

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [81]:
# Numpy los ejes, axes, axis, y dimensiones son lo mismo

In [82]:
a=np.arange(0,10).reshape(5,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [83]:
# a.T
a.transpose()

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [84]:
a=np.random.randint(0,36,5)
a

array([21, 27, 29,  3, 27])

In [85]:
a.sum()
a.min()
a.max()
a.std() #Desviacion estandar de nuestro arreglo
a.mean() # Media de nuestro arreglo

21.4

In [86]:
a.sort() # Ascendente

In [87]:
a

array([ 3, 21, 27, 27, 29])

In [88]:
inva= a[::-1] # Inversa del arreglo
inva

array([29, 27, 27, 21,  3])

In [89]:
def simple_operation(val):
  return val*10

In [90]:
np.vectorize(simple_operation)

In [91]:
func_vec = np.vectorize(simple_operation) #Vectorizando mi funcion

In [92]:
a

array([ 3, 21, 27, 27, 29])

In [93]:
func_vec(a)

array([ 30, 210, 270, 270, 290])

In [94]:
# CONOCER EL ID DE MI VARIABLE
id(a)

2473881802672

In [95]:
a

array([ 3, 21, 27, 27, 29])

In [96]:
b=a.view() # VISTA
b

array([ 3, 21, 27, 27, 29])

In [97]:
id(a), id(b)

(2473881802672, 2473881854576)

In [98]:
# Para ver si son el mismo objeto
a is b

False

In [99]:
b.base is a

True

In [100]:
id(a), id(b.base)

(2473881802672, 2473881802672)

In [101]:
# Una vista es el acceso a la informacion de un arreglo
b.flags

#OWNDATA : False => Es una vista

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [102]:
# COPIA DE UN ARREGLO
e=a.copy

In [103]:
e is a

False

In [104]:
# -----------
a

array([ 3, 21, 27, 27, 29])

In [105]:
fil = a < 20
fil

array([ True, False, False, False, False])

In [106]:
newa= a[fil]
newa

array([3])

In [107]:
newa= a[a < 20]
newa

array([3])

In [108]:
newa= a[(a < 20) & (a>5)]
newa

array([], dtype=int32)

In [109]:
newa= a[(a < 20) | (a == 30)]
newa

array([3])

In [110]:
# LEER Y ESCRIBIR ARCHIVOS
a=np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [111]:
# Guardar en un archivo mi data
np.savetxt('./ejemplo2.txt',a) # (ruta/nombre del archivo , arreglo)

In [112]:
np.loadtxt('./ejemplo2.txt')

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [121]:
np.savetxt('./ejemplo.csv',a,delimiter=";") # (ruta/nombre del archivo , arreglo)

In [122]:
np.loadtxt('./ejemplo.csv',delimiter=";")

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19.])

In [115]:
# genera un archivo binario
np.save('ejemplo.npy',a)

In [116]:
np.load('ejemplo.npy')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [117]:
# Almacenar en archivos binarios comprimidos
np.savez('ejemplo.npz',a)

In [118]:
np.load('ejemplo.npz')['arr_0']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [119]:
# Archivos pocos convencionales

In [120]:
# Para leer archivos de forma flexible
# skip_header=1 <> Que la lectura inicie despues de la fila 1
np.genfromtxt('./datasets/paises.txt', usecols=[1,2],skip_header=1, 
              comments="#", delimiter=",") # , skip_footer=0

array([[ 19.4284706 , -99.12127662],
       [ 19.0728302 ,  72.8826065 ],
       [ -4.        ,  40.        ],
       [ 22.        ,          nan],
       [-59.        , -51.75      ]])