# Modulo 2 - Practica Numpy & Pandas

# Numpys
* Listas son modificables
* puedo usar dtype = np.complex si necesito usar numeros con digitos extremadamente grandes
* Para representar vacios np.nan


In [175]:
# IMPORTAR LA LIBRERIA NUMPY
import numpy as np

In [176]:
lista =[1,2,3,4,5]
lista.append(10)
lista

[1, 2, 3, 4, 5, 10]

In [177]:
lista.remove(2)
lista

[1, 3, 4, 5, 10]

In [178]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [179]:
np.array([1,2,3,4,5],dtype=np.int)

<ipython-input-179-b430ad0de7ee>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array([1,2,3,4,5],dtype=np.int)


array([1, 2, 3, 4, 5])

In [180]:
a=np.array([1,2,3,4,5,'6'],dtype=np.int)
a

<ipython-input-180-5367d40d94c7>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a=np.array([1,2,3,4,5,'6'],dtype=np.int)


array([1, 2, 3, 4, 5, 6])

In [181]:
a=np.array([1,2,3,4,5,'6'],dtype=np.str)
a

<ipython-input-181-3cf816d21219>:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a=np.array([1,2,3,4,5,'6'],dtype=np.str)


array(['1', '2', '3', '4', '5', '6'], dtype='<U1')

In [182]:
a=np.array([1,2,3,4,5,'6'],dtype=np.float)
a

<ipython-input-182-6c185e153abb>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a=np.array([1,2,3,4,5,'6'],dtype=np.float)


array([1., 2., 3., 4., 5., 6.])

In [183]:
a=np.array([1,2,0,4,5,'6'],dtype=np.bool)
a

<ipython-input-183-3dd1bca0667e>:1: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a=np.array([1,2,0,4,5,'6'],dtype=np.bool)


array([ True,  True, False,  True,  True,  True])

In [184]:
np.array([1,2,0,4,5,'6'],dtype=np.uint) # Entero sin signo

array([1, 2, 0, 4, 5, 6], dtype=uint32)

In [185]:
# float32 <> Se refiere al tamanio de Bits que puede alcanzar un nro

In [186]:
np.array([1,2,0,4,5,'6'],dtype=np.complex) # Nro complejo

<ipython-input-186-877dc1649316>:1: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array([1,2,0,4,5,'6'],dtype=np.complex) # Nro complejo


array([1.+0.j, 2.+0.j, 0.+0.j, 4.+0.j, 5.+0.j, 6.+0.j])

In [187]:
# Arreglos de unos
a = np.ones(10, dtype=np.int)
print(a)

[1 1 1 1 1 1 1 1 1 1]


<ipython-input-187-77571883621c>:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a = np.ones(10, dtype=np.int)


In [188]:
# Arreglos de ceros
c = np.zeros(10, dtype=np.int)
print(c)

[0 0 0 0 0 0 0 0 0 0]


<ipython-input-188-d054c01104a6>:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  c = np.zeros(10, dtype=np.int)


In [189]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [190]:
np.random.randint(0,10,20)

array([4, 1, 0, 4, 9, 7, 3, 5, 6, 8, 3, 9, 8, 5, 7, 9, 5, 6, 7, 0])

In [191]:
print("tamano del elemento", a.size)

tamano del elemento 10


In [192]:
print("la forma del array", a.shape)

la forma del array (10,)


In [193]:
print("numero de dimensiones que posee el array", a.ndim)

numero de dimensiones que posee el array 1


In [194]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [195]:
print("la forma del array", b.shape)

la forma del array (2, 3)


In [196]:
print("numero de dimensiones que posee el array", b.ndim)

numero de dimensiones que posee el array 2


In [197]:
# Defomor el tamanio de una arreglo - valores inservible
# Arreglos con datos basura
# DEFINIR SOLO LA LONGITUD
b = np.empty(10, dtype=np.int)
print(b)

[0 0 0 0 1 0 2 0 3 0]


<ipython-input-197-5d1c783a0d75>:4: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  b = np.empty(10, dtype=np.int)


In [198]:
b[0] = 10
print(b)

[10  0  0  0  1  0  2  0  3  0]


In [199]:
# AXES

In [200]:
a = np.random.randint(0,100,20)
a

array([15, 70, 52, 55, 34,  7, 22, 23, 16, 89, 22, 11, 32, 85, 36, 26, 93,
       83, 67, 88])

In [201]:
np.nan

nan

In [202]:
a[0]

15

In [203]:
a[0:9]

array([15, 70, 52, 55, 34,  7, 22, 23, 16])

In [204]:
a[0:9:2]

array([15, 52, 34, 22, 16])

In [205]:
a[5:]

array([ 7, 22, 23, 16, 89, 22, 11, 32, 85, 36, 26, 93, 83, 67, 88])

In [206]:
a

array([15, 70, 52, 55, 34,  7, 22, 23, 16, 89, 22, 11, 32, 85, 36, 26, 93,
       83, 67, 88])

In [207]:
a[0], a[2], a[3]

(15, 52, 55)

In [208]:
a[[0,2,3]]

array([15, 52, 55])

In [209]:
b=np.append(a,100)

In [210]:
b

array([ 15,  70,  52,  55,  34,   7,  22,  23,  16,  89,  22,  11,  32,
        85,  36,  26,  93,  83,  67,  88, 100])

In [211]:
id(a)

2565599438096

In [212]:
id(b)

2565600968016

In [213]:
a is b

False

In [214]:
a

array([15, 70, 52, 55, 34,  7, 22, 23, 16, 89, 22, 11, 32, 85, 36, 26, 93,
       83, 67, 88])

In [215]:
b=np.delete(a,0)

In [216]:
a

array([15, 70, 52, 55, 34,  7, 22, 23, 16, 89, 22, 11, 32, 85, 36, 26, 93,
       83, 67, 88])

In [217]:
b

array([70, 52, 55, 34,  7, 22, 23, 16, 89, 22, 11, 32, 85, 36, 26, 93, 83,
       67, 88])

In [218]:
# Nomeclatura
# def suma_numeros():
#   pass

In [219]:
a

array([15, 70, 52, 55, 34,  7, 22, 23, 16, 89, 22, 11, 32, 85, 36, 26, 93,
       83, 67, 88])

In [220]:
a.sort()

In [221]:
a[::-1]

array([93, 89, 88, 85, 83, 70, 67, 55, 52, 36, 34, 32, 26, 23, 22, 22, 16,
       15, 11,  7])

In [222]:
a

array([ 7, 11, 15, 16, 22, 22, 23, 26, 32, 34, 36, 52, 55, 67, 70, 83, 85,
       88, 89, 93])

In [223]:
a.size

20

In [224]:
A = a.reshape(5,4) #Filas, Columnas

In [225]:
A

array([[ 7, 11, 15, 16],
       [22, 22, 23, 26],
       [32, 34, 36, 52],
       [55, 67, 70, 83],
       [85, 88, 89, 93]])

In [226]:
A.shape

(5, 4)

In [227]:
A.size

20

In [228]:
# Axies
# EJE 0 <> FILAS
# EJE 1 <> COLUMNAS

In [229]:
A[0,3]

16

In [230]:
A[4,3]

93

In [231]:
A[0]

array([ 7, 11, 15, 16])

In [232]:
A[0].sum()

49

In [233]:
A[0].size

4

In [234]:
A.max()

93

In [235]:
A[0].max()
A[0].min()

7

In [236]:
A[0].mean()
A[0].std()
A[0].sum()

49

In [237]:
A.T

array([[ 7, 22, 32, 55, 85],
       [11, 22, 34, 67, 88],
       [15, 23, 36, 70, 89],
       [16, 26, 52, 83, 93]])

In [238]:
A.T.shape

(4, 5)

In [239]:
A.T[2].sum()

233

In [240]:
A[:,2].sum()

233

In [241]:
A = a.reshape(5,4) #Filas, Columnas

In [242]:
A.flatten()
# Diferencia de ravel y flatten !
# https://frankgalandev.com/diferencias-entre-flatten-y-ravel-en-python/

array([ 7, 11, 15, 16, 22, 22, 23, 26, 32, 34, 36, 52, 55, 67, 70, 83, 85,
       88, 89, 93])

In [243]:
a = A.flatten()
a = np.random.randint(0,5,5)
a

array([3, 1, 4, 0, 4])

In [244]:
a[[0,4,3]]

array([3, 4, 0])

In [245]:
a[[True,True,False,False,True]]

array([3, 1, 4])

In [246]:
# OPERADORES LOGICOS

In [247]:
a<1

array([False, False, False,  True, False])

In [248]:
a[a>1]

array([3, 4, 4])

In [249]:
a = np.random.randint(0, 100, 200)
# a

In [250]:
a[(a>50) & (a<80)]

array([70, 65, 70, 68, 61, 67, 78, 58, 60, 75, 53, 51, 57, 68, 68, 52, 74,
       69, 61, 79, 73, 67, 55, 58, 64, 73, 58, 61, 63, 54, 56, 68, 69, 60,
       59, 64, 54, 56, 66, 79, 59, 79, 55, 78, 76, 58, 59, 73, 78, 79, 56,
       79, 54, 70, 54, 68, 77, 78])

In [251]:
np.arange(5,20,3)

array([ 5,  8, 11, 14, 17])

# Pandas
* Dataframe son arreglos pero con esteroides
* Pandas si usa numpys por eso es necesario primero aprender numpy

In [252]:
#importando pandas
import pandas as pd

In [253]:
# url = 'https://raw.githubusercontent.com/codigofacilito/pandas-python/master/users.csv'  # URL REPO PROFE
# url = 'https://raw.githubusercontent.com/MayumyCH/bootcamp_ciencia_de_datos/main/modulos/02.%20Introduccion%20al%20computo/Introduccion%20al%20analisis%20de%20datos%20con%20Python/datasets/user.csv'  # URL REPO bootcamp
url = 'https://raw.githubusercontent.com/MayumyCH/bootcamp_ciencia_de_datos/main/modulos/02.%20Intro%20al%20computo%20cientifico/datasets/user.csv'
# url = './user.csv' # URL de data cargada de mi maquina
# data = pd.read_csv(url, index_col='id')
data = pd.read_csv(url, index_col=0)

In [254]:
# Los primeros 3 elementos de la data
data.head(3)

name   age gender        country                     email
id                                                                        
0   Mr Jerome Thomas   NaN   male  United States                       NaN
1                NaN  70.0   male            NaN                       NaN
2    Mr Noham Dubois  40.0   male         France  noham.dubois@example.com

In [255]:
data.tail(3)

name   age  gender      country                       email
id                                                                            
197   Mr Gabriel Berger  40.0    male       France  gabriel.berger@example.com
198  Mrs Ülkü Tanrıkulu  37.0  female       Turkey  ulku.tanrikulu@example.com
199     Mr Raff Valkema  60.0    male  Netherlands    raff.valkema@example.com

In [256]:
data['name']
data['age']
data.age

id
0       NaN
1      70.0
2      40.0
3      63.0
4      61.0
       ... 
195    46.0
196    40.0
197    40.0
198    37.0
199    60.0
Name: age, Length: 200, dtype: float64

## LOC AND ILOC

In [257]:
# INDICE
data.iloc[4]

name                Mr Damien Marchand
age                               61.0
gender                            male
country                         France
email      damien.marchand@example.com
Name: 4, dtype: object

In [258]:
# INDICE
C = data.iloc[[4,5,6]]
C

name   age gender  country                        email
id                                                                       
4   Mr Damien Marchand  61.0   male   France  damien.marchand@example.com
5     Mr Harri Althoff  56.0   male  Germany    harri.althoff@example.com
6        Mr Noah Olsen  40.0   male  Denmark       noah.olsen@example.com

In [259]:
type(C)

pandas.core.frame.DataFrame

In [260]:
C = data.iloc[4]
type(C)

pandas.core.series.Series

In [261]:
# data

In [262]:
# data.loc['Mr Harri Althoff']
#quitando NaN
data = data.dropna()
data

name   age  gender      country  \
id                                                   
2       Mr Noham Dubois  40.0    male       France   
3     Mrs Naja Johansen  63.0  female      Denmark   
4    Mr Damien Marchand  61.0    male       France   
5      Mr Harri Althoff  56.0    male      Germany   
6         Mr Noah Olsen  40.0    male      Denmark   
..                  ...   ...     ...          ...   
195       Mr Raul Bravo  46.0    male        Spain   
196   Miss Maeva Fortin  40.0  female       Canada   
197   Mr Gabriel Berger  40.0    male       France   
198  Mrs Ülkü Tanrıkulu  37.0  female       Turkey   
199     Mr Raff Valkema  60.0    male  Netherlands   

                           email  
id                                
2       noham.dubois@example.com  
3      naja.johansen@example.com  
4    damien.marchand@example.com  
5      harri.althoff@example.com  
6         noah.olsen@example.com  
..                           ...  
195       raul.bravo@example.com  
196     maeva.fortin@example.com  
197   gabriel.berger@example.com  
198   ulku.tanrikulu@example.com  
199     raff.valkema@example.com  

[198 rows x 5 columns]

## Ejercicios en clase:

![]()

In [263]:
# url = 'https://raw.githubusercontent.com/MayumyCH/bootcamp_ciencia_de_datos/main/modulos/02.%20Introduccion%20al%20computo/Introduccion%20al%20analisis%20de%20datos%20con%20Python/datasets/user.csv'  # URL REPO bootcamp
url = 'https://raw.githubusercontent.com/MayumyCH/bootcamp_ciencia_de_datos/main/modulos/02.%20Intro%20al%20computo%20cientifico/datasets/user.csv'

data = pd.read_csv(url, index_col='name')

In [264]:
data

id   age  gender        country  \
name                                                   
Mr Jerome Thomas      0   NaN    male  United States   
NaN                   1  70.0    male            NaN   
Mr Noham Dubois       2  40.0    male         France   
Mrs Naja Johansen     3  63.0  female        Denmark   
Mr Damien Marchand    4  61.0    male         France   
...                 ...   ...     ...            ...   
Mr Raul Bravo       195  46.0    male          Spain   
Miss Maeva Fortin   196  40.0  female         Canada   
Mr Gabriel Berger   197  40.0    male         France   
Mrs Ülkü Tanrıkulu  198  37.0  female         Turkey   
Mr Raff Valkema     199  60.0    male    Netherlands   

                                          email  
name                                             
Mr Jerome Thomas                            NaN  
NaN                                         NaN  
Mr Noham Dubois        noham.dubois@example.com  
Mrs Naja Johansen     naja.johansen@example.com  
Mr Damien Marchand  damien.marchand@example.com  
...                                         ...  
Mr Raul Bravo            raul.bravo@example.com  
Miss Maeva Fortin      maeva.fortin@example.com  
Mr Gabriel Berger    gabriel.berger@example.com  
Mrs Ülkü Tanrıkulu   ulku.tanrikulu@example.com  
Mr Raff Valkema        raff.valkema@example.com  

[200 rows x 5 columns]

In [265]:
data= data.dropna()
# data

## Resolución de los Ejercicios

### 1ra Pregunta

In [271]:
# url = 'https://raw.githubusercontent.com/MayumyCH/bootcamp_ciencia_de_datos/main/modulos/02.%20Introduccion%20al%20computo/Introduccion%20al%20analisis%20de%20datos%20con%20Python/datasets/user.csv'  # URL REPO bootcamp
url = 'https://raw.githubusercontent.com/MayumyCH/bootcamp_ciencia_de_datos/main/modulos/02.%20Intro%20al%20computo%20cientifico/datasets/user.csv'

data = pd.read_csv(url, index_col='name')
data= data.dropna()

In [272]:
# 1RA PREGUNTA
#
data[data['age']>40]
# data.query('age > 40')

id   age  gender      country  \
name                                                   
Mrs Naja Johansen       3  63.0  female      Denmark   
Mr Damien Marchand      4  61.0    male       France   
Mr Harri Althoff        5  56.0    male      Germany   
Mr Jakob Russell        8  44.0    male      Ireland   
Miss Emilia Laitinen    9  53.0  female      Finland   
...                   ...   ...     ...          ...   
Mr Noah Moore         191  44.0    male  New Zealand   
Ms Delphine Ginnish   193  58.0  female       Canada   
Madame Rosa Lefevre   194  67.0  female  Switzerland   
Mr Raul Bravo         195  46.0    male        Spain   
Mr Raff Valkema       199  60.0    male  Netherlands   

                                             email  
name                                                
Mrs Naja Johansen        naja.johansen@example.com  
Mr Damien Marchand     damien.marchand@example.com  
Mr Harri Althoff         harri.althoff@example.com  
Mr Jakob Russell         jakob.russell@example.com  
Miss Emilia Laitinen   emilia.laitinen@example.com  
...                                            ...  
Mr Noah Moore               noah.moore@example.com  
Ms Delphine Ginnish   delphine.ginnish@example.com  
Madame Rosa Lefevre       rosa.lefevre@example.com  
Mr Raul Bravo               raul.bravo@example.com  
Mr Raff Valkema           raff.valkema@example.com  

[120 rows x 5 columns]

### 2da Pregunta

In [273]:
# url = 'https://raw.githubusercontent.com/MayumyCH/bootcamp_ciencia_de_datos/main/modulos/02.%20Introduccion%20al%20computo/Introduccion%20al%20analisis%20de%20datos%20con%20Python/datasets/user.csv'  # URL REPO bootcamp
data = pd.read_csv(url, index_col='id')
data= data.dropna()

In [274]:
data[data['age']>40]['name']

id
3         Mrs Naja Johansen
4        Mr Damien Marchand
5          Mr Harri Althoff
8          Mr Jakob Russell
9      Miss Emilia Laitinen
               ...         
191           Mr Noah Moore
193     Ms Delphine Ginnish
194     Madame Rosa Lefevre
195           Mr Raul Bravo
199         Mr Raff Valkema
Name: name, Length: 120, dtype: object

In [275]:
# 2da PREGUNTA
#
# data[(data['age']>40) & (data['gender'] == 'female')]
data.query('age > 40 and gender == "female"')

name   age  gender         country  \
id                                                           
3          Mrs Naja Johansen  63.0  female         Denmark   
9       Miss Emilia Laitinen  53.0  female         Finland   
10       Ms Cathriona Hanson  53.0  female         Ireland   
11          Miss Maia Clarke  52.0  female     New Zealand   
12         Ms Cathy Simmmons  55.0  female       Australia   
..                       ...   ...     ...             ...   
181           Mrs Avery King  57.0  female  United Kingdom   
182          Mrs Soila Silva  63.0  female          Brazil   
190  Miss Margrietha Holster  61.0  female     Netherlands   
193      Ms Delphine Ginnish  58.0  female          Canada   
194      Madame Rosa Lefevre  67.0  female     Switzerland   

                              email  
id                                   
3         naja.johansen@example.com  
9       emilia.laitinen@example.com  
10     cathriona.hanson@example.com  
11          maia.clarke@example.com  
12       cathy.simmmons@example.com  
..                              ...  
181          avery.king@example.com  
182         soila.silva@example.com  
190  margrietha.holster@example.com  
193    delphine.ginnish@example.com  
194        rosa.lefevre@example.com  

[68 rows x 5 columns]

### 3ra Pregunta

In [276]:
data

name   age  gender      country  \
id                                                   
2       Mr Noham Dubois  40.0    male       France   
3     Mrs Naja Johansen  63.0  female      Denmark   
4    Mr Damien Marchand  61.0    male       France   
5      Mr Harri Althoff  56.0    male      Germany   
6         Mr Noah Olsen  40.0    male      Denmark   
..                  ...   ...     ...          ...   
195       Mr Raul Bravo  46.0    male        Spain   
196   Miss Maeva Fortin  40.0  female       Canada   
197   Mr Gabriel Berger  40.0    male       France   
198  Mrs Ülkü Tanrıkulu  37.0  female       Turkey   
199     Mr Raff Valkema  60.0    male  Netherlands   

                           email  
id                                
2       noham.dubois@example.com  
3      naja.johansen@example.com  
4    damien.marchand@example.com  
5      harri.althoff@example.com  
6         noah.olsen@example.com  
..                           ...  
195       raul.bravo@example.com  
196     maeva.fortin@example.com  
197   gabriel.berger@example.com  
198   ulku.tanrikulu@example.com  
199     raff.valkema@example.com  

[198 rows x 5 columns]

In [277]:
### 3ra Pregunta
#
data[~data['email'].str.endswith('@example.com')]
# data.query('~email.str.contains("@example.com")')

name   age gender country                 email
id                                                           
151  Mr Thomas Lam  42.0   male  Canada  thomas.lam@gmail.com

In [278]:
# data.query('email.str.contains("@example")')

In [279]:
## WHERE - SELECT

### 4ta Pregunta

In [280]:
## 4ta Pregunta
#
# data[(data['country']== 'Germany') | 
#      (data['country'] == 'Finland') | 
#      (data['country'] == 'Canada')]

# data[(data['country'].isin(["Germany","Finland","Canada"]))]
data.query('country in ("Germany","Finland","Canada")')

name   age  gender  country  \
id                                                   
5          Mr Harri Althoff  56.0    male  Germany   
7         Ms Britta Weinert  35.0  female  Germany   
9      Miss Emilia Laitinen  53.0  female  Finland   
20     Mr Vincenzo Rauscher  25.0    male  Germany   
21            Mr Louis Ross  60.0    male   Canada   
31          Mr Toivo Kotila  27.0    male  Finland   
36          Mr Anthony Wong  42.0    male   Canada   
38        Mrs Lotta Rintala  26.0  female  Finland   
41         Miss Iida Ketola  46.0  female  Finland   
45        Ms Ilona Moilanen  22.0  female  Finland   
47         Miss Ellen Rinne  66.0  female  Finland   
50           Mr Theo Miller  33.0    male   Canada   
53          Ms Aino Lassila  54.0  female  Finland   
56       Ms Marcella Brosch  38.0  female  Germany   
58       Miss Madison Ennis  49.0  female   Canada   
72           Ms Megan Brown  26.0  female   Canada   
79   Ms Hanne Aschenbrenner  64.0  female  Germany   
85       Mrs Luisa Weißmann  32.0  female  Germany   
87         Mr Joona Koskela  59.0    male  Finland   
88            Mrs Hilda Epp  22.0  female  Germany   
131          Mr Xavier Addy  30.0    male   Canada   
133      Miss Julia Ambrose  34.0  female   Canada   
144        Ms Mareile Plate  51.0  female  Germany   
147         Mr Lauri Kotila  32.0    male  Finland   
151           Mr Thomas Lam  42.0    male   Canada   
158   Mr Rafael Spangenberg  33.0    male  Germany   
170           Mr Ryder Côté  25.0    male   Canada   
174       Ms Isla Koistinen  37.0  female  Finland   
184      Mr Philip Bélanger  24.0    male   Canada   
193     Ms Delphine Ginnish  58.0  female   Canada   
196       Miss Maeva Fortin  40.0  female   Canada   

                               email  
id                                    
5          harri.althoff@example.com  
7         britta.weinert@example.com  
9        emilia.laitinen@example.com  
20     vincenzo.rauscher@example.com  
21            louis.ross@example.com  
31          toivo.kotila@example.com  
36          anthony.wong@example.com  
38         lotta.rintala@example.com  
41           iida.ketola@example.com  
45        ilona.moilanen@example.com  
47           ellen.rinne@example.com  
50           theo.miller@example.com  
53          aino.lassila@example.com  
56       marcella.brosch@example.com  
58         madison.ennis@example.com  
72           megan.brown@example.com  
79   hanne.aschenbrenner@example.com  
85       luisa.weissmann@example.com  
87         joona.koskela@example.com  
88             hilda.epp@example.com  
131          xavier.addy@example.com  
133        julia.ambrose@example.com  
144        mareile.plate@example.com  
147         lauri.kotila@example.com  
151             thomas.lam@gmail.com  
158   rafael.spangenberg@example.com  
170           ryder.cote@example.com  
174       isla.koistinen@example.com  
184      philip.belanger@example.com  
193     delphine.ginnish@example.com  
196         maeva.fortin@example.com

In [281]:
data[(data['country'].isin(["Germany","Finland","Canada"]))].count()

name       31
age        31
gender     31
country    31
email      31
dtype: int64

### 5ta Pregunta

In [282]:
### 5ta Pregunta
##
# data[(data['gender'] == 'female') & (data['country']== "Germany")]
data.query('gender == "female" and country == "Germany" ')

name   age  gender  country  \
id                                                   
7         Ms Britta Weinert  35.0  female  Germany   
56       Ms Marcella Brosch  38.0  female  Germany   
79   Ms Hanne Aschenbrenner  64.0  female  Germany   
85       Mrs Luisa Weißmann  32.0  female  Germany   
88            Mrs Hilda Epp  22.0  female  Germany   
144        Ms Mareile Plate  51.0  female  Germany   

                               email  
id                                    
7         britta.weinert@example.com  
56       marcella.brosch@example.com  
79   hanne.aschenbrenner@example.com  
85       luisa.weissmann@example.com  
88             hilda.epp@example.com  
144        mareile.plate@example.com

### 6ta Pregunta

In [283]:
### 6ta Pregunta
##
data[(data['gender']=='male') & (data['country']=='Canada')].count()
data[(data['gender']=='male') & (data['country']=='Canada')]['gender'].count()

7

In [284]:
data.query('gender == "male" and country == "Canada" ')

name   age gender country                        email
id                                                                       
21        Mr Louis Ross  60.0   male  Canada       louis.ross@example.com
36      Mr Anthony Wong  42.0   male  Canada     anthony.wong@example.com
50       Mr Theo Miller  33.0   male  Canada      theo.miller@example.com
131      Mr Xavier Addy  30.0   male  Canada      xavier.addy@example.com
151       Mr Thomas Lam  42.0   male  Canada         thomas.lam@gmail.com
170       Mr Ryder Côté  25.0   male  Canada       ryder.cote@example.com
184  Mr Philip Bélanger  24.0   male  Canada  philip.belanger@example.com

### 7ma Pregunta

In [285]:
### 7ma Pregunta
##
data.groupby('gender')['gender'].count()

gender
female    106
male       92
Name: gender, dtype: int64

In [286]:
data.groupby('gender').count().index

Index(['female', 'male'], dtype='object', name='gender')

In [287]:
data.groupby('gender').count().index.values

array(['female', 'male'], dtype=object)

In [288]:
data.groupby('gender')['gender'].count()

gender
female    106
male       92
Name: gender, dtype: int64

In [289]:
data.value_counts(data['gender']) # MUCHO MEJOR !!!!

gender
female    106
male       92
dtype: int64

In [290]:
# data.groupby('gender')[''].agg({'count':'gender'}) # NO FUNCIONA

# data.groupby('gender').agg({'gender':'count'}) # OK
data.groupby('gender')['gender'].agg('count') # OK
# PENDIENTE 

gender
female    106
male       92
Name: gender, dtype: int64

### 8va Pregunta

**Encontrar el pais con mas mujeres**
* Filtra mujeres
* Agrupa segun pais los ya filtrado
* Cuenta solos elementos de pais

In [291]:
data[data['gender']=='female'].groupby('country')['country'].count()

country
Australia          6
Brazil             5
Canada             5
Denmark           12
Finland            7
France             4
Germany            6
Iran               5
Ireland            6
Netherlands        4
New Zealand       10
Norway             6
Spain              9
Switzerland        6
Turkey             7
United Kingdom     6
United States      2
Name: country, dtype: int64

* Ordena la tabla agrupada por pais de manera descentende
* Solo me importa tener el primer encabezado

In [292]:
data[data['gender']=='female'].groupby('country')['country'].count(
).sort_values(ascending=False).head(3)

country
Denmark        12
New Zealand    10
Spain           9
Name: country, dtype: int64

### 9na Pregunta

Obtener los 5 pais con mas usuarios

In [293]:
data.groupby('country')['country'].count().sort_values(ascending=False).head(5)

country
Ireland           16
Denmark           16
New Zealand       14
United Kingdom    14
Norway            14
Name: country, dtype: int64

In [294]:
type(data.groupby('country')['country'].count())

pandas.core.series.Series